
CREATE DATABASE IF NOT EXISTS sdc;

USE sdc;

CREATE TABLE IF NOT EXISTS products (
  product_id INT UNSIGNED NOT NULL PRIMARY KEY,
  zero INT UNSIGNED NOT NULL DEFAULT 0,
  one INT UNSIGNED NOT NULL DEFAULT 0,
  two INT UNSIGNED NOT NULL DEFAULT 0,
  three INT UNSIGNED NOT NULL DEFAULT 0,
  four INT UNSIGNED NOT NULL DEFAULT 0,
  five INT UNSIGNED NOT NULL DEFAULT 0,
  recommended INT UNSIGNED NOT NULL DEFAULT 0,
  review_count INT UNSIGNED NOT NULL DEFAULT 0,
);

CREATE TABLE IF NOT EXIST characteristics (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id INT UNSIGNED NOT NULL,
  characteristic VARCHAR(16) NOT NULL,
  average_value FLOAT(23) NOT NULL DEFAULT 0,
  FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
);

CREATE TABLE IF NOT EXISTS reviews (
  review_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id INT UNSIGNED NOT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  recommended BOOL NOT NULL,
  response VARCHAR(120),
  summary VARCHAR(60) NOT NULL,
  body TEXT(1000) NOT NULL,
  r_date DATE NOT NULL,
  reviewer_name VARCHAR(60) NOT NULL,
  reviewer_email VARCHAR(60) NOT NULL,
  helpfulness INT UNSIGNED NOT NULL,
  FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_characteristics (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  review_id INT UNSIGNED NOT NULL,
  characteristic_id INT UNSIGNED NOT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  FOREIGN KEY review_id REFERENCES reviews(review_id) ON DELETE CASCADE,
  FOREIGN KEY characteristic_id REFERENCES characteristics(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS photos (
  photo_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(255),
  review_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (review_id) REFERENCES reviews(review_id) ON DELETE CASCADE
);

